In [2]:
import pandas as pd
import numpy as np
from sklearn import svm
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import LeaveOneGroupOut
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report

In [3]:
df = pd.read_csv("dataset_eeg_nseg.csv")

In [4]:
df.drop(['Unnamed: 0'],axis=1, inplace=True)

In [5]:
df = df.set_index(['id_user','session','video'])

In [6]:
df

0         1         2         3         4  \
id_user session video                                                     
10      1       1      0.000056  0.000210  0.000578  0.001068  0.001386   
                2      0.000073  0.000045  0.000349  0.000667  0.000553   
                3      0.000053  0.000243  0.000697  0.000991  0.000822   
                4      0.000032  0.000114  0.000367  0.000646  0.000741   
                5      0.000037  0.000115  0.000549  0.000856  0.000560   
...                         ...       ...       ...       ...       ...   
9       3       20     0.000005  0.000028  0.000144  0.000136  0.000052   
                21     0.000012  0.000020  0.000093  0.000228  0.000360   
                22     0.000006  0.000026  0.000080  0.000192  0.000179   
                23     0.000035  0.000116  0.000271  0.000244  0.000255   
                24     0.000016  0.000144  0.000096  0.000285  0.000275   

                              5         6         7         8         9  ...  \
id_user session video                                                    ...   
10      1       1      0.001648  0.000803  0.000437  0.000751  0.000383  ...   
                2      0.000305  0.000502  0.000579  0.000626  0.000521  ...   
                3      0.000288  0.000170  0.000315  0.000519  0.000392  ...   
                4      0.000520  0.000351  0.000349  0.000443  0.000537  ...   
                5      0.000430  0.000418  0.000234  0.000129  0.000227  ...   
...                         ...       ...       ...       ...       ...  ...   
9       3       20     0.000212  0.000210  0.000047  0.000127  0.000165  ...   
                21     0.000446  0.000264  0.000091  0.000087  0.000094  ...   
                22     0.000068  0.000094  0.000052  0.000129  0.000117  ...   
                23     0.000180  0.000203  0.000097  0.000168  0.000173  ...   
                24     0.000113  0.000217  0.000480  0.000640  0.000708  ...   

                           5502      5503      5504      5505      5506  \
id_user session video                                                     
10      1       1      0.680894  0.677372  0.678587  0.680154  0.679000   
                2      0.681449  0.680814  0.681055  0.679858  0.679219   
                3      0.680556  0.679891  0.680421  0.680982  0.680714   
                4      0.681528  0.681170  0.682441  0.681751  0.681922   
                5      0.681270  0.679830  0.681256  0.682198  0.681864   
...                         ...       ...       ...       ...       ...   
9       3       20     0.683626  0.684026  0.683992  0.683872  0.683737   
                21     0.683333  0.683626  0.683485  0.683547  0.683689   
                22     0.683917  0.683562  0.683447  0.683692  0.683361   
                23     0.683632  0.683680  0.683738  0.683844  0.683406   
                24     0.683428  0.683518  0.683481  0.683462  0.683615   

                           5507      5508      5509      5510  emotion  
id_user session video                                                   
10      1       1      0.679539  0.679375  0.678674  0.680591        1  
                2      0.680615  0.676147  0.680797  0.679779        2  
                3      0.680317  0.680449  0.680310  0.679916        3  
                4      0.682117  0.682258  0.681055  0.681194        0  
                5      0.680023  0.680439  0.680000  0.679143        2  
...                         ...       ...       ...       ...      ...  
9       3       20     0.683521  0.683858  0.683820  0.683911        0  
                21     0.683664  0.683373  0.683693  0.684037        2  
                22     0.683313  0.683518  0.684135  0.684174        0  
                23     0.683448  0.683663  0.683562  0.683567        1  
                24     0.684293  0.684325  0.684048  0.683871        0  

[1080 rows x 5512 columns]

## Split train e test
### Subject Dependent
16 trials train e 8 test
2 testing group for labels 

In [36]:
def split_sub_dep(df):    
    df_sd = df.reset_index()
    # generiamo 8 video su cui eseguiamo i test
    test_videos = np.random.randint(1, 25, size=8)
    print(test_videos)
    X_testSD = df_sd[df_sd['video'].isin(test_videos)]
    print(X_testSD.emotion.unique()) #check se sono rappresentate tutte le emozioni
    X_testSD.set_index(['id_user','session','video'], inplace=True)
    y_testSD = X_testSD.emotion
    X_testSD = X_testSD.drop(['emotion'],axis=1)
    X_trainSD = df_sd[~df_sd['video'].isin(test_videos)]
    X_trainSD.set_index(['id_user','session','video'], inplace=True)
    y_trainSD = X_trainSD.emotion
    X_trainSD = X_trainSD.drop(['emotion'],axis=1)
    return X_trainSD,y_trainSD,X_testSD,y_testSD

In [37]:
X_trainSD,y_trainSD,X_testSD,y_testSD = split_sub_dep(df)

[ 8  1  3 11 17 16 20 15]
[1 3 2 0]


In [80]:
clfSD = GradientBoostingClassifier(n_estimators=10, learning_rate=0.5, max_depth=2,random_state=0).fit(X_trainSD, y_trainSD)

In [81]:
clfSD.score(X_testSD, y_testSD)

0.20833333333333334

In [82]:
clfSD.score(X_trainSD, y_trainSD)

0.8069444444444445

In [77]:
rfSD = RandomForestClassifier(n_estimators=10, max_depth=10,random_state=42).fit(X_trainSD, y_trainSD)

In [83]:
rfSD.score(X_testSD, y_testSD)

0.24722222222222223

In [84]:
rfSD.score(X_trainSD, y_trainSD)

0.9319444444444445

### Subject Indipendent
Leave One Out Cross Validation sugli utenti

In [85]:
def SubjectIndipendent_GBC(df):
    df_SI = df.reset_index()
    groups = df_SI['id_user']
    X_SI = df_SI.drop(['emotion','id_user','session','video'],axis=1)
    y_SI = df_SI.emotion
    return X_SI,y_SI,groups

In [86]:
X_SI,y_SI,groups = SubjectIndipendent_GBC(df)

In [87]:
df_SI = df.reset_index()
groups = df_SI['id_user']

In [88]:
groups

0       10
1       10
2       10
3       10
4       10
        ..
1075     9
1076     9
1077     9
1078     9
1079     9
Name: id_user, Length: 1080, dtype: int64

In [89]:
X_SI = df_SI.drop(['emotion','id_user','session','video'],axis=1)

In [90]:
X_SI

0         1         2         3         4         5         6  \
0     0.000056  0.000210  0.000578  0.001068  0.001386  0.001648  0.000803   
1     0.000073  0.000045  0.000349  0.000667  0.000553  0.000305  0.000502   
2     0.000053  0.000243  0.000697  0.000991  0.000822  0.000288  0.000170   
3     0.000032  0.000114  0.000367  0.000646  0.000741  0.000520  0.000351   
4     0.000037  0.000115  0.000549  0.000856  0.000560  0.000430  0.000418   
...        ...       ...       ...       ...       ...       ...       ...   
1075  0.000005  0.000028  0.000144  0.000136  0.000052  0.000212  0.000210   
1076  0.000012  0.000020  0.000093  0.000228  0.000360  0.000446  0.000264   
1077  0.000006  0.000026  0.000080  0.000192  0.000179  0.000068  0.000094   
1078  0.000035  0.000116  0.000271  0.000244  0.000255  0.000180  0.000203   
1079  0.000016  0.000144  0.000096  0.000285  0.000275  0.000113  0.000217   

             7         8         9  ...      5501      5502      5503  \
0     0.000437  0.000751  0.000383  ...  0.681325  0.680894  0.677372   
1     0.000579  0.000626  0.000521  ...  0.680923  0.681449  0.680814   
2     0.000315  0.000519  0.000392  ...  0.680739  0.680556  0.679891   
3     0.000349  0.000443  0.000537  ...  0.681769  0.681528  0.681170   
4     0.000234  0.000129  0.000227  ...  0.682273  0.681270  0.679830   
...        ...       ...       ...  ...       ...       ...       ...   
1075  0.000047  0.000127  0.000165  ...  0.683606  0.683626  0.684026   
1076  0.000091  0.000087  0.000094  ...  0.683356  0.683333  0.683626   
1077  0.000052  0.000129  0.000117  ...  0.683923  0.683917  0.683562   
1078  0.000097  0.000168  0.000173  ...  0.683325  0.683632  0.683680   
1079  0.000480  0.000640  0.000708  ...  0.684066  0.683428  0.683518   

          5504      5505      5506      5507      5508      5509      5510  
0     0.678587  0.680154  0.679000  0.679539  0.679375  0.678674  0.680591  
1     0.681055  0.679858  0.679219  0.680615  0.676147  0.680797  0.679779  
2     0.680421  0.680982  0.680714  0.680317  0.680449  0.680310  0.679916  
3     0.682441  0.681751  0.681922  0.682117  0.682258  0.681055  0.681194  
4     0.681256  0.682198  0.681864  0.680023  0.680439  0.680000  0.679143  
...        ...       ...       ...       ...       ...       ...       ...  
1075  0.683992  0.683872  0.683737  0.683521  0.683858  0.683820  0.683911  
1076  0.683485  0.683547  0.683689  0.683664  0.683373  0.683693  0.684037  
1077  0.683447  0.683692  0.683361  0.683313  0.683518  0.684135  0.684174  
1078  0.683738  0.683844  0.683406  0.683448  0.683663  0.683562  0.683567  
1079  0.683481  0.683462  0.683615  0.684293  0.684325  0.684048  0.683871  

[1080 rows x 5511 columns]

In [91]:
y_SI = df_SI.emotion

In [92]:
y_SI

0       1
1       2
2       3
3       0
4       2
       ..
1075    0
1076    2
1077    0
1078    1
1079    0
Name: emotion, Length: 1080, dtype: int64

#### GradientBoostingClassifier

In [98]:
model = GradientBoostingClassifier(n_estimators=10, learning_rate=1, max_depth=5, random_state=0)

In [141]:
rfc = RandomForestClassifier(n_estimators=15, max_depth=10,random_state=22)

In [99]:
logo = LeaveOneGroupOut()

In [100]:
logo.get_n_splits(X_SI, y_SI, groups)

15

In [142]:
scores = cross_val_score(rfc, X_SI, y_SI, cv=logo, verbose=1 , groups = groups, n_jobs = -1)

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 6 concurrent workers.
[Parallel(n_jobs=-1)]: Done  15 out of  15 | elapsed:    1.5s finished


In [102]:
scores

array([0.23611111, 0.23611111, 0.27777778, 0.27777778, 0.19444444,
       0.19444444, 0.40277778, 0.20833333, 0.27777778, 0.34722222,
       0.31944444, 0.25      , 0.36111111, 0.34722222, 0.33333333])

In [103]:
scori = pd.DataFrame(scores)
scori.to_csv("scores.csv")

In [143]:
scores.mean()

0.30185185185185187

### Subject-Biased Experiment
train_test_split

In [105]:
X_trainSB, X_testSB, y_trainSB, y_testSB = train_test_split(df.drop('emotion',axis=1), df.emotion, test_size=0.20, random_state=42)

In [106]:
X_testSB

0         1         2         3         4  \
id_user session video                                                     
12      2       16     0.000008  0.000516  0.001592  0.001822  0.000997   
2       2       21     0.000044  0.000083  0.000462  0.000881  0.000616   
10      3       12     0.000004  0.000221  0.001332  0.001077  0.001250   
4       2       13     0.000041  0.000582  0.001236  0.001804  0.001213   
8       3       20     0.000019  0.000152  0.000867  0.000711  0.000663   
...                         ...       ...       ...       ...       ...   
15      3       4      0.000264  0.003635  0.011254  0.026212  0.034113   
3       3       5      0.000052  0.000990  0.005577  0.007492  0.004512   
11      3       10     0.000042  0.000452  0.000954  0.001051  0.000518   
12      2       2      0.001472  0.002333  0.002836  0.001935  0.002303   
6       1       12     0.002084  0.009313  0.034888  0.038752  0.053693   

                              5         6         7         8         9  ...  \
id_user session video                                                    ...   
12      2       16     0.000759  0.000655  0.000465  0.000272  0.000379  ...   
2       2       21     0.000625  0.000695  0.000345  0.000285  0.000335  ...   
10      3       12     0.001647  0.001343  0.001021  0.000802  0.001383  ...   
4       2       13     0.001718  0.001550  0.000670  0.001938  0.002067  ...   
8       3       20     0.001260  0.000807  0.000318  0.000180  0.000170  ...   
...                         ...       ...       ...       ...       ...  ...   
15      3       4      0.023178  0.020101  0.015724  0.013238  0.012309  ...   
3       3       5      0.001709  0.000602  0.000192  0.000045  0.000024  ...   
11      3       10     0.000569  0.000533  0.000323  0.000296  0.000306  ...   
12      2       2      0.003605  0.003672  0.002514  0.003084  0.003106  ...   
6       1       12     0.053539  0.022970  0.010090  0.004948  0.009943  ...   

                           5501      5502      5503      5504      5505  \
id_user session video                                                     
12      2       16     0.679390  0.679000  0.680738  0.681477  0.682194   
2       2       21     0.680934  0.680750  0.681149  0.681431  0.683091   
10      3       12     0.683215  0.683885  0.683958  0.681566  0.681321   
4       2       13     0.685096  0.682800  0.681938  0.679263  0.680470   
8       3       20     0.682209  0.681293  0.681397  0.682452  0.684373   
...                         ...       ...       ...       ...       ...   
15      3       4      0.683563  0.681009  0.681083  0.682396  0.681954   
3       3       5      0.684386  0.685066  0.683596  0.683723  0.684183   
11      3       10     0.684231  0.684988  0.684215  0.684507  0.684945   
12      2       2      0.681952  0.682234  0.680857  0.681086  0.680220   
6       1       12     0.679582  0.679402  0.682288  0.682428  0.682942   

                           5506      5507      5508      5509      5510  
id_user session video                                                    
12      2       16     0.683832  0.684749  0.684386  0.685085  0.685086  
2       2       21     0.681742  0.682150  0.682481  0.682143  0.680051  
10      3       12     0.682477  0.682076  0.684267  0.684585  0.684663  
4       2       13     0.675999  0.678645  0.681212  0.682752  0.679215  
8       3       20     0.682326  0.680113  0.680362  0.681406  0.681989  
...                         ...       ...       ...       ...       ...  
15      3       4      0.679835  0.679746  0.680190  0.680423  0.683104  
3       3       5      0.684328  0.683982  0.683199  0.683741  0.683496  
11      3       10     0.684918  0.684578  0.685511  0.684433  0.684279  
12      2       2      0.682603  0.680384  0.682912  0.682397  0.682267  
6       1       12     0.685962  0.684435  0.683224  0.685342  0.686171  

[216 rows x 5511 columns]

#### GradientBoostingClassifier

In [131]:
clf = GradientBoostingClassifier(n_estimators=12, learning_rate=0.2, max_depth=3, random_state=24).fit(X_trainSB, y_trainSB)

In [132]:
clf.score(X_testSB, y_testSB)

0.3611111111111111

In [133]:
clf.score(X_trainSB, y_trainSB)

0.9016203703703703

In [163]:
rfc = RandomForestClassifier(n_estimators=10, max_depth=5,random_state=22).fit(X_trainSB, y_trainSB)

In [164]:
rfc.score(X_testSB, y_testSB)

0.33796296296296297

In [165]:
rfc.score(X_trainSB, y_trainSB)

0.6550925925925926

# GRADIENT BOOSTING ON ONE FEATURE
### PSD

In [166]:
df = pd.read_csv("dataset_eeg_psds.csv")
df.drop(['Unnamed: 0'],axis=1, inplace=True)
df = df.set_index(['id_user','session','video'])

In [167]:
df

0         1          2          3          4  \
id_user session video                                                        
10      1       1      0.952755  3.834360  10.721228  19.887183  25.824439   
                2      2.393555  1.443329  11.871719  22.774562  18.887957   
                3      1.489037  7.202926  20.856213  29.713532  24.614091   
                4      0.905984  3.543481  11.645386  20.604895  23.629156   
                5      1.370372  4.415421  21.411094  33.434142  21.845199   
...                         ...       ...        ...        ...        ...   
9       3       20     0.457711  3.349578  17.589614  16.559618   6.258637   
                21     0.644106  1.202051   5.968025  14.754987  23.375220   
                22     0.540826  2.809283   8.986773  21.860166  20.385859   
                23     2.890024  9.788639  22.987859  20.691225  21.647931   
                24     0.471703  4.913602   3.242203   9.858747   9.511241   

                               5          6          7          8          9  \
id_user session video                                                          
10      1       1      30.715281  14.928749   8.090955  13.951526   7.070147   
                2      10.355057  17.133717  19.765291  21.365868  17.781661   
                3       8.567110   5.005052   9.369096  15.508441  11.682358   
                4      16.567218  11.142225  11.079863  14.100062  17.095886   
                5      16.761699  16.284967   9.088370   4.955161   8.809823   
...                          ...        ...        ...        ...        ...   
9       3       20     25.875669  25.595647   5.699863  15.477017  20.101218   
                21     28.982387  17.146680   5.808435   5.575698   6.014293   
                22      7.608486  10.691958   5.785502  14.618375  13.320158   
                23     15.249477  17.169880   8.146258  14.209363  14.635962   
                24      3.831531   7.480618  16.649001  22.263723  24.623149   

                       ...      2997      2998      2999      3000      3001  \
id_user session video  ...                                                     
10      1       1      ... -0.086706 -0.086706 -0.086706 -0.086706 -0.086706   
                2      ... -0.095146 -0.095146 -0.095146 -0.095146 -0.095146   
                3      ... -0.092203 -0.092203 -0.092203 -0.092203 -0.092203   
                4      ... -0.107096 -0.107096 -0.107096 -0.107096 -0.107096   
                5      ... -0.078886 -0.078886 -0.078886 -0.078886 -0.078886   
...                    ...       ...       ...       ...       ...       ...   
9       3       20     ... -0.100242 -0.100242 -0.100242 -0.100242 -0.100242   
                21     ... -0.109461 -0.109461 -0.109461 -0.109461 -0.109461   
                22     ... -0.134824 -0.134824 -0.134824 -0.134824 -0.134824   
                23     ... -0.099847 -0.099847 -0.099847 -0.099847 -0.099847   
                24     ... -0.100633 -0.100633 -0.100633 -0.100633 -0.100633   

                           3002      3003      3004      3005  emotion  
id_user session video                                                   
10      1       1     -0.086706 -0.086706 -0.086706 -0.086706        1  
                2     -0.095146 -0.095146 -0.095146 -0.095146        2  
                3     -0.092203 -0.092203 -0.092203 -0.092203        3  
                4     -0.107096 -0.107096 -0.107096 -0.107096        0  
                5     -0.078886 -0.078886 -0.078886 -0.078886        2  
...                         ...       ...       ...       ...      ...  
9       3       20    -0.100242 -0.100242 -0.100242 -0.100242        0  
                21    -0.109461 -0.109461 -0.109461 -0.109461        2  
                22    -0.134824 -0.134824 -0.134824 -0.134824        0  
                23    -0.099847 -0.099847 -0.099847 -0.099847        1  
                24    -0.100633 -0.100633 -0.100633 -0.10

## DEPENDENCY

In [232]:
X_trainSD,y_trainSD,X_testSD,y_testSD = split_sub_dep(df)

[14  5 14  3  2 15 10 14]
[2 3 1 0]


In [224]:
clfSD = GradientBoostingClassifier(n_estimators=20, learning_rate=0.2, max_depth=2,random_state=22).fit(X_trainSD, y_trainSD)

In [225]:
clfSD.score(X_trainSD, y_trainSD)

0.8915032679738563

In [226]:
clfSD.score(X_testSD, y_testSD)

0.25396825396825395

In [186]:
y_pred = clfSD.predict(X_testSD)

In [187]:
print(classification_report(y_testSD,y_pred))

              precision    recall  f1-score   support

           0       0.41      0.20      0.27       120
           1       0.18      0.13      0.15        75
           2       0.16      0.67      0.26        30
           3       0.33      0.29      0.31        90

    accuracy                           0.25       315
   macro avg       0.27      0.32      0.25       315
weighted avg       0.31      0.25      0.25       315



In [262]:
rfc = RandomForestClassifier(n_estimators=30, max_depth=6,random_state=42).fit(X_trainSD, y_trainSD)

In [263]:
rfc.score(X_trainSD, y_trainSD)

0.8061728395061728

In [264]:
rfc.score(X_testSD, y_testSD)

0.24074074074074073

## INDIPENDENCY

In [265]:
X_SI,y_SI,groups = SubjectIndipendent_GBC(df)

In [46]:
model = GradientBoostingClassifier(n_estimators=20, learning_rate=1, max_depth=15, random_state=0)
logo = LeaveOneGroupOut()
logo.get_n_splits(X_SI, y_SI, groups)
scores = cross_val_score(model, X_SI, y_SI, cv=logo, verbose=1 , groups = groups, n_jobs = -1)
print(scores.mean())

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 6 concurrent workers.
[Parallel(n_jobs=-1)]: Done  15 out of  15 | elapsed:  5.6min finished


0.31851851851851853


In [266]:
model = RandomForestClassifier(n_estimators=30, max_depth=6,random_state=42)
logo = LeaveOneGroupOut()
logo.get_n_splits(X_SI, y_SI, groups)
scores = cross_val_score(model, X_SI, y_SI, cv=logo, verbose=1 , groups = groups, n_jobs = -1)
print(scores.mean())

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 6 concurrent workers.
[Parallel(n_jobs=-1)]: Done  15 out of  15 | elapsed:    3.1s finished


0.32500000000000007


## BIAS

In [275]:
X_trainSB, X_testSB, y_trainSB, y_testSB = train_test_split(df.drop('emotion',axis=1), df.emotion, test_size=0.20, random_state=42)

In [280]:
clf = GradientBoostingClassifier(n_estimators=10, learning_rate=0.1, max_depth=3, random_state=0).fit(X_trainSB, y_trainSB)

In [281]:
clf.score(X_testSB, y_testSB)

0.28703703703703703

In [282]:
clf.score(X_trainSB, y_trainSB)

0.7604166666666666

In [270]:
rfc = RandomForestClassifier(n_estimators=30, max_depth=6,random_state=42).fit(X_trainSB, y_trainSB)

In [271]:
rfc.score(X_testSB,y_testSB)

0.3472222222222222

In [278]:
rfc.score(X_trainSB,y_trainSB)

0.8067129629629629

# GRADIENT BOOSTING ON ONE FEATURE
### DE

In [283]:
df = pd.read_csv("dataset_eeg_des.csv")
df.drop(['Unnamed: 0'],axis=1, inplace=True)
df = df.set_index(['id_user','session','video'])

In [284]:
df

0         1         2         3         4  \
id_user session video                                                     
10      1       1      2.135436  2.887686  3.465504  3.810436  3.955764   
                2      2.549241  2.254038  3.489210  3.876865  3.767604   
                3      2.436902  3.456774  4.163457  4.401829  4.272075   
                4      1.841611  2.513253  3.124816  3.421180  3.492676   
                5      2.320207  2.961560  3.857012  4.111162  3.868319   
...                         ...       ...       ...       ...       ...   
9       3       20     1.398441  2.604782  3.687751  3.648057  3.009953   
                21     1.571485  1.894192  2.786308  3.305627  3.571761   
                22     1.270886  2.200624  2.915375  3.471395  3.427353   
                23     2.621798  3.373337  3.905828  3.839850  3.868095   
                24     1.494128  3.076038  2.783606  3.572978  3.547337   

                              5         6         7         8         9  ...  \
id_user session video                                                    ...   
10      1       1      4.053275  3.646478  3.300221  3.606062  3.223825  ...   
                2      3.407996  3.706311  3.790671  3.835916  3.726078  ...   
                3      3.567253  3.214838  3.632954  3.966298  3.774067  ...   
                4      3.306529  3.099885  3.100102  3.221046  3.320871  ...   
                5      3.717754  3.698447  3.367067  3.021535  3.351307  ...   
...                         ...       ...       ...       ...       ...  ...   
9       3       20     3.942856  3.935395  2.950334  3.604765  3.776026  ...   
                21     3.696536  3.393062  2.770488  2.746998  2.790538  ...   
                22     2.811443  3.023582  2.642579  3.219103  3.161054  ...   
                23     3.649109  3.723545  3.259310  3.605300  3.623675  ...   
                24     2.896757  3.371674  3.948618  4.159415  4.232633  ...   

                            492       493       494       495       496  \
id_user session video                                                     
10      1       1     -1.011859 -1.020659 -0.602725 -0.584323 -0.602491   
                2     -0.654046 -0.287855 -0.064083 -0.382718 -0.854156   
                3     -0.102593 -0.080281 -0.138853  0.001005 -0.083322   
                4     -0.990079 -0.927056 -0.745584 -0.978420 -1.031638   
                5     -0.247413 -0.758625 -1.643860 -1.252678 -0.605932   
...                         ...       ...       ...       ...       ...   
9       3       20    -0.389243 -0.347923 -0.460666 -0.483391 -0.797307   
                21    -0.804578 -1.045797 -1.104529 -0.949304 -0.719607   
                22    -0.531922 -0.662631 -0.867511 -1.125926 -0.903615   
                23    -0.544234 -0.343033 -0.551949 -0.976702 -1.112032   
                24    -0.602491  0.003543  0.088560 -0.193022 -0.742112   

                            497       498       499       500  emotion  
id_user session video                                                   
10      1       1     -0.579400 -1.200410 -0.910379 -1.369580        1  
                2     -0.538963 -0.978321 -0.520367 -1.108300        2  
                3     -0.067288 -0.063967  0.042125 -0.123110        3  
                4     -0.682465 -0.665910 -1.033460 -1.373817        0  
                5     -0.750933 -1.202377 -0.686867 -1.160245        2  
...                         ...       ...       ...       ...      ...  
9       3       20    -0.593601 -0.401147 -0.498099 -0.751132        0  
                21    -0.668664 -0.650504 -0.838495 -1.361561        2  
                22    -1.054831 -0.916811 -1.142544 -1.251611        0  
                23    -0.834240 -0.739685 -0.623760 -1.128035        1  
                24    -1.026718 -0.977749 -0.960097 -1.363363        0  

[1080 rows x 502 columns]

## DEPENDENCY

In [285]:
X_trainSD,y_trainSD,X_testSD,y_testSD = split_sub_dep(df)

[10  9  2 14 11 18  4  7]
[2 0 1 3]


In [302]:
clfSD = GradientBoostingClassifier(n_estimators=20, learning_rate=0.2, max_depth=2,random_state=10).fit(X_trainSD, y_trainSD)

In [303]:
clfSD.score(X_trainSD, y_trainSD)

0.8652777777777778

In [304]:
clfSD.score(X_testSD, y_testSD)

0.3472222222222222

In [314]:
rfc = RandomForestClassifier(n_estimators=30, max_depth=5,random_state=42).fit(X_trainSD, y_trainSD)

In [315]:
rfc.score(X_trainSD, y_trainSD)

0.8125

In [316]:
rfc.score(X_testSD, y_testSD)

0.3

In [65]:
y_pred = clfSD.predict(X_testSD)

In [66]:
print(classification_report(y_testSD,y_pred))

              precision    recall  f1-score   support

           0       0.54      1.00      0.70       120
           1       0.98      0.59      0.73        75
           2       1.00      0.45      0.62        75
           3       0.96      0.61      0.75        90

    accuracy                           0.70       360
   macro avg       0.87      0.66      0.70       360
weighted avg       0.83      0.70      0.70       360



## INDIPENDENCY

In [317]:
X_SI,y_SI,groups = SubjectIndipendent_GBC(df)

In [320]:
model = GradientBoostingClassifier(n_estimators=20, learning_rate=0.1, max_depth=15, random_state=0)
logo = LeaveOneGroupOut()
logo.get_n_splits(X_SI, y_SI, groups)
scores = cross_val_score(model, X_SI, y_SI, cv=logo, verbose=1 , groups = groups, n_jobs = -1)
print(scores.mean())

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 6 concurrent workers.


0.274074074074074


[Parallel(n_jobs=-1)]: Done  15 out of  15 | elapsed:  1.5min finished


In [321]:
model = RandomForestClassifier(n_estimators=30, max_depth=5,random_state=42)
logo = LeaveOneGroupOut()
logo.get_n_splits(X_SI, y_SI, groups)
scores = cross_val_score(model, X_SI, y_SI, cv=logo, verbose=1 , groups = groups, n_jobs = -1)
print(scores.mean())

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 6 concurrent workers.


0.34444444444444444


[Parallel(n_jobs=-1)]: Done  15 out of  15 | elapsed:    0.6s finished


## BIAS

In [322]:
X_trainSB, X_testSB, y_trainSB, y_testSB = train_test_split(df.drop('emotion',axis=1), df.emotion, test_size=0.20, random_state=42)

In [329]:
clf = GradientBoostingClassifier(n_estimators=10, learning_rate=0.1, max_depth=3, random_state=0).fit(X_trainSB, y_trainSB)

In [330]:
clf.score(X_testSB, y_testSB)

0.32407407407407407

In [331]:
clf.score(X_trainSB, y_trainSB)

0.7662037037037037

In [332]:
rfc = RandomForestClassifier(n_estimators=30, max_depth=5,random_state=42).fit(X_trainSB,y_trainSB)

In [333]:
rfc.score(X_testSB,y_testSB)

0.33796296296296297

In [335]:
rfc.score(X_trainSB,y_trainSB)

0.8182870370370371

# GRADIENT BOOSTING ON ONE FEATURE
### ASM

In [ ]:
df = pd.read_csv("dataset_eeg_asms.csv")
df.drop(['Unnamed: 0'],axis=1, inplace=True)
df = df.set_index(['id_user','session','video'])

In [ ]:
df

## DEPENDENCY

In [ ]:
X_trainSD,y_trainSD,X_testSD,y_testSD = split_sub_dep(df)

In [ ]:
clfSD = GradientBoostingClassifier(n_estimators=10, learning_rate=0.1, max_depth=2,random_state=0).fit(X_trainSD, y_trainSD)

In [ ]:
clfSD.score(X_testSD, y_testSD)

In [ ]:
y_pred = clfSD.predict(X_testSD)

In [ ]:
print(classification_report(y_testSD,y_pred))

## INDIPENDENCY

In [ ]:
X_SI,y_SI,groups = SubjectIndipendent_GBC(df)

In [ ]:
model = GradientBoostingClassifier(n_estimators=20, learning_rate=1, max_depth=15, random_state=0)
logo = LeaveOneGroupOut()
logo.get_n_splits(X_SI, y_SI, groups)
scores = cross_val_score(model, X_SI, y_SI, cv=logo, verbose=1 , groups = groups, n_jobs = -1)
print(scores.mean())

## BIAS

In [ ]:
X_trainSB, X_testSB, y_trainSB, y_testSB = train_test_split(df.drop('emotion',axis=1), df.emotion, test_size=0.20, random_state=42)

In [ ]:
clf = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0, max_depth=3, random_state=0).fit(X_trainSB, y_trainSB)

In [ ]:
clf.score(X_testSB, y_testSB)

# GRADIENT BOOSTING ON ONE FEATURE
### DASM

In [ ]:
df = pd.read_csv("dataset_eeg_dasms.csv")
df.drop(['Unnamed: 0'],axis=1, inplace=True)
df = df.set_index(['id_user','session','video'])

In [ ]:
df

## DEPENDENCY

In [ ]:
X_trainSD,y_trainSD,X_testSD,y_testSD = split_sub_dep(df)

In [ ]:
clfSD = GradientBoostingClassifier(n_estimators=10, learning_rate=0.1, max_depth=2,random_state=0).fit(X_trainSD, y_trainSD)

In [ ]:
clfSD.score(X_testSD, y_testSD)

In [ ]:
y_pred = clfSD.predict(X_testSD)

In [ ]:
print(classification_report(y_testSD,y_pred))

## INDIPENDENCY

In [ ]:
X_SI,y_SI,groups = SubjectIndipendent_GBC(df)

In [ ]:
model = GradientBoostingClassifier(n_estimators=20, learning_rate=1, max_depth=15, random_state=0)
logo = LeaveOneGroupOut()
logo.get_n_splits(X_SI, y_SI, groups)
scores = cross_val_score(model, X_SI, y_SI, cv=logo, verbose=1 , groups = groups, n_jobs = -1)
print(scores.mean())

## BIAS

In [ ]:
X_trainSB, X_testSB, y_trainSB, y_testSB = train_test_split(df.drop('emotion',axis=1), df.emotion, test_size=0.20, random_state=42)

In [ ]:
clf = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0, max_depth=3, random_state=0).fit(X_trainSB, y_trainSB)

In [ ]:
clf.score(X_testSB, y_testSB)